export const openings_data = [
    {
      "id": 1,
      "role": "Social Media Manager",
      "reqId": "T0000001",
      "posted": "20/7/2023",
      "address": "Remote WFH(Work From Home)",
      "responsibilities":"Understanding the needs, preferences, and behaviors of users through research methods like surveys, interviews, and usability testing. This helps inform design decisions and ensure the user interface meets user expectations.Working closely with UX designers, developers, product managers, and other stakeholders to ensure the design aligns with project goals and technical constraints. This often involves communicating design ideas and making adjustments based on feedback.Creating and maintaining design systems and style guides to ensure consistency across the product. This includes defining reusable components, patterns, and standards for design. Preparing design specifications and assets for handoff to developers. This includes providing detailed documentation and supporting the implementation process.",
      "experienceReqd": "3 years",
      "salaryPackage": "5LPA-7LPA",
    },
    {
      "id": 2,
      "role": "UI/UX Designer",
      "reqId": "T0000002",
      "posted": "15/8/2023",
      "address": "Remote WFH(Work From Home)",
      "responsibilities":"Understanding the needs, preferences, and behaviors of users through research methods like surveys, interviews, and usability testing. This helps inform design decisions and ensure the user interface meets user expectations.Working closely with UX designers, developers, product managers, and other stakeholders to ensure the design aligns with project goals and technical constraints. This often involves communicating design ideas and making adjustments based on feedback.Creating and maintaining design systems and style guides to ensure consistency across the product. This includes defining reusable components, patterns, and standards for design. Preparing design specifications and assets for handoff to developers. This includes providing detailed documentation and supporting the implementation process.",
      "experienceReqd": "2 years",
      "salaryPackage": "4.5LPA-6LPA",
    },
    {
      "id": 3,
      "role": "Content Designer",
      "reqId": "T0000003",
      "posted": "21/10/2023",
      "address": "Remote WFH(Work From Home)",
      "responsibilities":"Understanding the needs, preferences, and behaviors of users through research methods like surveys, interviews, and usability testing. This helps inform design decisions and ensure the user interface meets user expectations.Working closely with UX designers, developers, product managers, and other stakeholders to ensure the design aligns with project goals and technical constraints. This often involves communicating design ideas and making adjustments based on feedback.Creating and maintaining design systems and style guides to ensure consistency across the product. This includes defining reusable components, patterns, and standards for design. Preparing design specifications and assets for handoff to developers. This includes providing detailed documentation and supporting the implementation process.",
      "experienceReqd": "Fresher/ Entry Level",
      "salaryPackage": "2.5LPA-3.5LPA",
    },
    {
      "id": 4,
      "role": "Video Editor",
      "reqId": "T0000004",
      "posted": "22/10/2023",
      "address": "Remote WFH(Work From Home)",
      "responsibilities":"Understanding the needs, preferences, and behaviors of users through research methods like surveys, interviews, and usability testing. This helps inform design decisions and ensure the user interface meets user expectations.Working closely with UX designers, developers, product managers, and other stakeholders to ensure the design aligns with project goals and technical constraints. This often involves communicating design ideas and making adjustments based on feedback.Creating and maintaining design systems and style guides to ensure consistency across the product. This includes defining reusable components, patterns, and standards for design. Preparing design specifications and assets for handoff to developers. This includes providing detailed documentation and supporting the implementation process.",
      "experienceReqd": "2 years",
      "salaryPackage": "3LPA-4LPA",
    },
  ]
  